# spring configuration
spring:
   application:
      name: mysite
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
            
   #mvc
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
#      view:
#         prefix: /WEB-INF/views/
#         suffix: .jsp
 #        exposeContextBeansAsAttributes: true
         
   web:
      resources:
         static-locations: classpath:/assets/, file:/Users/nabi/Study/poscodx2023/00tools/mysite-uploads/
   
   #multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB

   # message resources(internationalization, i18n)
   messages:
      always-use-message-format: true
      basename: web/messages/messages   
      encoding: utf-8
   
   # aop
   aop:
      auto: true
      proxy-target-class: true
            
   #datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/shopping_db?charset=utf8
      username: shopping
      password: shopping
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true

# logging
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: /Users/nabi/Study/poscodx2023/00tools/${spring.application.name}-logs/exception.%d{yyyy-MM-dd}.%i.log.zip
         max-file-size: 200MB
         max-history: 10 
   file: /Users/nabi/Study/poscodx2023/00tools/${spring.application.name}-logs/exception.log
   level:
      root: INFO
      com:
         poscodx:
            mysite:
               exception: ERROR